services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - .env.db

  backend:
    container_name: backend
    build: ./backend
    image: backend
    ports:
      - "8000:8000"
    restart: on-failure
    command: bash -c "
      while !</dev/tcp/postgres/5432; do sleep 1; done;
      alembic upgrade head;
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
    env_file:
      - .env
      - .env.db
    volumes:
      - ./backend/src:/src

volumes:
  postgres_data:
